paths:
  raw_data: "data/raw/trajectories.npy"
  processed_data: "data/processed/"
  splits: "data/splits/"
  tul_classifier: "models/tul_classifier/model.h5"
  checkpoints: "models/checkpoints/"
  results: "results/metrics/"
  visualizations: "results/visualizations/"

data:
  max_length: 144
  lat_centroid: 39.9042
  lon_centroid: 116.4074
  scale_factor: 0.01
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

model:
  latent_dim: 100
  keys: ["lat_lon", "day", "hour", "category", "mask"]
  vocab_size:
    lat_lon: 2
    day: 7
    hour: 24
    category: 10
    mask: 1
  num_heads: 8
  num_transformer_blocks: 4
  ff_dim_multiplier: 4

training:
  batch_size: 256
  epochs: 200
  learning_rate: 0.0001
  beta_1: 0.5
  reward_weights:
    w1: 1.0  # Adversarial reward weight
    w2: 1.0  # Utility reward weight
    w3: 1.0  # Privacy reward weight
  ppo:
    epsilon: 0.2
    gamma: 0.99
    gae_lambda: 0.95
  early_stopping:
    patience: 20
    min_delta: 0.001

evaluation:
  privacy:
    metrics: ["acc1", "acc5", "macro_p", "macro_r", "macro_f1"]
  utility:
    metrics: ["fid", "jsd"]
    jsd_weights:
      lat_lon: 0.4
      day: 0.2
      hour: 0.2
      category: 0.2 