_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
architecture:
    value: RL_Enhanced_Transformer_TrajGAN
batch_size:
    value: 256
category_size:
    value: 2052
early_stopping:
    value:
        min_delta: 0.001
        patience: 20
early_stopping_patience:
    value: 20
epochs:
    value: 2000
lat_centroid:
    value: 40.76114086870136
latent_dim:
    value: 100
lon_centroid:
    value: -73.96855971611322
max_length:
    value: 144
reward_weights:
    value:
        adversarial: 0.5
        privacy: 0.5
        utility: 0.5
rl_params:
    value:
        clip_epsilon: 0.2
        gae_lambda: 0.95
        gamma: 0.99
        ppo_epochs: 4
scale_factor:
    value: 0.3010842838867802
